### ISSUE TITLE
NetworkController API normalization: Add `rollbackToPreviousProvider` method.

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1024]
We should add a method for rolling back to the previous provider config. This can be useful for handling connection failures when switching to a network.

This is part of [a larger effort to normalize the API of both network controllers](https://github.com/MetaMask/controllers/issues/971), to make them easier to merge.

**Comment by adonesky1** [comment]
I realize this might be out of scope for this issue, but since `NetworkConfigurations` now live on the `NetworkController` rather than keeping a record of the full previous provider config, should we just keep a record of either the provider `type` (in the case of an infura network) or the `[networkConfigurationId](https://github.com/MetaMask/core/pull/1064/files#diff-ea0aa37793484e278bd59970b7a6ce8380b75b723b34612081d402fb66261cfdR462)` (in the case of a custom network) and then use either `[setProviderType](https://github.com/MetaMask/core/blob/ade7255cfdcf6104cf1071bf8a4d227e7fa3d7d0/packages/network-controller/src/NetworkController.ts#L441)` or `[setActiveNetwork](https://github.com/MetaMask/core/pull/1064/files#diff-ea0aa37793484e278bd59970b7a6ce8380b75b723b34612081d402fb66261cfdR464)` to roll it back? cc @Gudahtt @mcmire

**Comment by Gudahtt** [comment]
That would make sense to me! The method of rolling back is an internal implementation detail, we don't need it to match the extension. And for the previous provider state, we don't need to store that as controller state at all. I had planned on removing it from the extension ([in this PR](https://github.com/MetaMask/metamask-extension/pull/16923)) since we don't use it anywhere except in the implementation of this method.

**Comment by adonesky1** [comment]
> And for the previous provider state, we don't need to store that as controller state at all

Ah yea we don't need it persisted to localStorage since its only ever relevant when attempting to change networks.
