### ISSUE TITLE
Plan tasks to consolidate keyring interactions between extension and mobile.

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#1103]
We should plan out how to consolidate keyring interactions between extension and mobile.

The issue #1102 exists for researching what the current differences are. The goal of this issue would be planning out a way to merge them together.

### Definition of Done
- Whenever applies, any change unit tested, reviewed(approved) and documented(JSDOC at least)
- [ ] We have changelog entries for any related changes
- [ ] Any changed APIs have comprehensive inline documentation
- [ ] Any changed public APIs are well covered by unit tests
- Other items
- [ ] If a planning/research ticket, then the plan has been reviewed and approved by at least 1 team members

**Comment by xinnanyemm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Shared-Libraries-621e46b4d7103800171d1b02/issues/MetaMask/core/1103?planning-poker) with Zenhub @cryptodev-2s @Gudahtt @mikesposito

**Comment by mikesposito** [comment]
## Prerequisites

This is a list of the changes we should make prior to any other method change:

- #1151
- #1152

**Comment by mikesposito** [comment]
## addNewAccount
This method is present on both core KeyringController and extension, we should align them.

###  Make `addNewAccount`  method idempotent
#### Context
The extension `addNewAccount` takes an `accountCount` parameter: a new account is added only if its value is equal to the number of identities in the preferences controller store.  In the core KeyringController we don’t have this parameter and the account is directly added to the primary keyring. This has been done to make this method idempotent for MV3 compatibility reasons (See [Pull Request #15566](https://github.com/MetaMask/metamask-extension/pull/15566)).

#### Proposal
In order to make the KeyringController compatible with MV3 we should bring this change.

### Change `addNewAccount` method returned objects
#### Context
Currently, the core KeyringController's `addNewAccount` method returns `EthKeyringController.fullUpdate()` directly, but what we expect on the clients is different in both cases:
- On mobile, the core KeyringController [is patched](https://github.com/MetaMask/metamask-mobile/blob/main/patches/%40metamask%2Bkeyring-controller%2B1.0.1.patch) to return the following object:
```typescript
{
    keyringState: ReturnType<EthKeyringController['fullUpdate']>,
    addedAccountAddress: string
}
```

- On the extension, the `addNewAccount` method returns a union of the EthKeyringController's memStore and the identities from the preferencesController.

#### Proposal
At the moment, none of the clients is compatible with what is returned by the core KeyringController. Based on the [Redux actions file](https://github.com/MetaMask/metamask-extension/blob/develop/ui/store/actions.ts#L437), the extension's UI uses identities returned by the `addNewAccount` background method to then locally compute the new account, roughly seeing which one was not present before.

In the core KeyringController's `addNewAccount` we could return an object similar to the one expected by the mobile client, adding an `addedAccountAddress` value with the new account added. This would be compliant with the mobile client and beneficial for the extension, as it will have that value already computed. 

Moreover, with this solution, we also remove the extension's dependency from the preferencesController in this method, which we should have treated somehow otherwise.

**Comment by mikesposito** [comment]
## verifySeedPhrase
This method is present on both core KeyringController and extension, we should align them.

### Seed phrase should be handled as array of integers instead of string
#### Context
In the extension, the primary keyring mnemonic is handled as buffer. In the core KeyringController it is handled as a string. (See https://github.com/MetaMask/metamask-extension/commit/98f187c301176152a7f697e62e2ba6d78b018b68)

#### Proposal
We should handle it as an array of integers in the core KeyringController too.

**Comment by mikesposito** [comment]
## 5: importAccountWithStrategy
### 5.1: Use `AccountImportStrategy` enum also in the extension
#### Context
API for this method are different, as strategy argument keys used to identify strategies are different: es. “Private Key” in the extension, “privateKey” in the core KeyringController.
#### Proposal
We should use the core KeyringController’s  `AccountImportStrategy` enum also in the extension (`privateKey` and `json`):

```typescript
enum AccountImportStrategy {
  privateKey = 'privateKey',
  json = 'json',
}
```

### 5.2: Add private key digits check on core KeyringController
#### Context
For strategy private key, additionally to `isValidPrivate`, the extension  also checks the number of digits in the string (See [Pull Request #17763](https://github.com/MetaMask/metamask-extension/pull/17763))
#### Proposal
We can add this check to the core KeyringController.

### 5.3: Change function return
#### Context
In the mobile client, the core KeyringController is patched (see also method `addAccount`) to return this object:
```typescript
{
    keyringState: KeyringMemState,
    importedAccountAddress: string
}
``` 

#### Proposal
We can use a solution similar to the one provided for `addAccount`. We can choose to use the same `addedAccountAddress` used for `addAccount`, or use a specific one, like `importedAccountAddress`.

### 5.4: Support optional parameter to not change selected account
#### Context
In the mobile client,  the core KeyringController is patched to not switch account after creating a new one.
#### Proposal
We can add an optional parameter to the function, or an `opt` object, to let the clients specify if the new account has should be also selected.

**Comment by mikesposito** [comment]
## 6: setLocked
### 6.1: Hardware keyrings’ disposals should remain in the extension
#### Context
In the extension,  `ledgerKeyring.destroy` and `trezorKeyring.dispose` methods are called to lock hardware keyrings, before calling EthKeyringController ’s `setLocked` method.
#### Proposal
We should leave this responsibility to the extension client for now.

### 6.2: Session storage clearing should also remain in the extension
#### Context
For MV3 compatibility, in the extension clearLoginArtifacts() is also called to remove login data from the browser session storage.
#### Proposal
As for **6.1**, this responsibility should remain with the extension.

**Comment by mikesposito** [comment]
## 7: createNewVaultAndKeychain
### 7.1: Leave to the extension the responsibility to avoid multiple UI submissions 
#### Context
To resolve a “possible bug” and to avoid potential multiple submissions from the UI, on the extension there’s a check to see if the vault has been already created by checking accounts in the EthKeyringController (See: [Pull Request #2605](https://github.com/MetaMask/metamask-extension/pull/2605))
#### Proposal
As the vault creation in the core KeyringController is already done behind a mutex, we should leave the multiple UI submission to the clients.

**Comment by mikesposito** [comment]
## 8. createNewVaultAndRestore
### 8.1: Seed phrase should be passed as array of bytes
#### Context
In the extension, the seed phrase is passed expected by this method is an array of bytes, on core KeyringController is expected as string
#### Proposal
We should expect an array of bytes also in the core KeyringController

### 8.2: Leave clearing calls to the extension  
#### Context
Besides clearing the addresses in the preferencesController (done also on mobile side), we call the following “clearing” controllers methods:
 - snapController.clearState
 - notificationController.clear
 - accountTracker.clearAccounts
 - cachedBalancesController.clearCachedBalances
 - txController.txStateManager.clearUnapprovedTxs

These are not present on the core KeyringController.
We should also note that some of these like snapController.clearState are under the FLASK feature flag on the extension.
#### Proposal
We should leave these responsibilities to the extension client

### 8.3: Leave account re-creation and balance fetching to the extension
#### Context
In the extension, after creating a new vault, accounts are restored up until the first found with 0 balance (that is then removed)
#### Proposal
This seems to be an extension client requirement, so it would make sense to not give this responsibility to the core KeyringController, leaving it in the extension.

### 8.4: Leave Ledger transport preference update to the extension
#### Context
In the extension, the transportPreference for the ledger keyring is updated after creating the vault.
#### Proposal
This should remain in the extension for now, there is ongoing [PR](https://github.com/MetaMask/core/issues/1102) for adding ledger support.

**Comment by mikesposito** [comment]
## 9. submitPassword
### 9.1:  Leave latest block check in the extension
#### Context
In the extension, after submitting the password to `EthKeyringController.submitPassword`, there is a check for the latest block using `blockTracker`.
#### Proposal
We should leave this check in the extension after unlocking the wallet.

### 9.2:  Leave Ledger `tranpostPreference` update in the extension
#### Context
In the extension, the  `transportPreference` for the ledger keyring is also updated:
```typescript
// This must be set as soon as possible to communicate to the
// keyring's iframe and have the setting initialized properly
// Optimistically called to not block MetaMask login due to
// Ledger Keyring GitHub downtime
const transportPreference =
  this.preferencesController.getLedgerTransportPreference();
```
#### Proposal
We should leave this call in the extension for now.

**Comment by mikesposito** [comment]
## 10: submitEncryptionKey
This method is not present in the core KeyringController.
It is used by the extension to keep the user logged in when the browser service worker restarts. 

#### Proposal
This is needed with MV3 and we should port this to the core KeyringController. This method calls `EthKeyringController.submitEncryptionKey`

**Comment by mikesposito** [comment]
## 11: verifyPassword
This method is in the extension, but not in the core KeyringController.
The closest method declared in the core KeyringController is named `validatePassword`, but with some differences:
* In the extension, we call and return `EthKeyringController.verifyPassword` (this method is never used in the core alternative)
* In the core KeyringController: we return `#keyring.password === password`

#### Proposal
Leave the core KeyringController method `validatePassword` as is, and add the `verifyPassword` from the extension in the core KeyringController as an additional method.

**Comment by mikesposito** [comment]
## 12: QR Devices methods
### 12.1: Instantiate the QR keyring through the core KeyringController
#### Context
The QRHardwareKeyring is instantiated differently on the two clients: On extension we manually create a new QRHardwareKeyring in `metamask-controller.js`, instead on core KeyringController it’s done when any of the QR-related methods is called, using the `getOrAddQRKeyring` method that instantiates a new QR Keyring if none is present. 

#### Proposal
If the extension starts to use QR methods from the core KeyringController, the client will not need to instantiate a QR keyring manually.

### Rename submitQRHardwareCryptoHDKey in the extension
#### Context
In core KeyringController, this method is called `submitQRCryptoHDKey`
#### Proposal
We can refactor the extension to use the core KeyringController’s method.

### Rename submitQRHardwareCryptoAccount in the extension
#### Context
In core KeyringController, this method is called `submitQRCryptoAccount`
#### Proposal
We can refactor the extension to use the core KeyringController’s method.

### Add cancelSyncQRHardware in the core 
#### Context
Seems like the `cancelSyncQRHardware` used in the extension is missing from the core KeyringController.  
#### Proposal
We should add this method to the core KeyringController, named `cancelQRHardwareSync` to be aligned with the others. This method should call `QRHardwareKeyring.cancelSync`.

### Rename submitQRHardwareSignature in the extension
#### Context
In core KeyringController, this method is called `submitQRSignature`
#### Proposal
We can refactor the extension to use the core KeyringController’s method.

### Rename cancelQRHardwareSignRequest in the extension
#### Context
In core KeyringController, this method is called `cancelQRSignRequest`
#### Proposal
We can refactor the extension to use the core KeyringController’s method.

**Comment by mikesposito** [comment]
## 14: EthKeyringController instantiation 
### 14.1: Add `cacheEncryptionKey ` when creating EthKeyringController instance
#### Context
In the extension, the EthKeyringController instance is created with this config:
```typescript
{
  keyringBuilders: additionalKeyrings,
  initState: initState.KeyringController,
  encryptor: opts.encryptor || undefined,
  cacheEncryptionKey: isManifestV3,
}
``` 
On the other hand, the core KeyringController’s `KeyringConfig` type seems to not expect the `cacheEncryptionKey` property.
#### Proposal
We should add `cacheEncryptionKey` to the core KeyringController’s `KeyringConfig` type, so that it will be passed to EthKeyringController constructor.

### 14.2: Allow memStore event subscription
#### Context
Right after instantiating the EthKeyringController, the extension subscribes to three keyring events: `onLock`, `onUnlock` and to `memStore` observable. 
The core KeyringController has `onLock`, `onUnlock` and `subscribe` methods to do that, but `subscribe` subscribes to the store, not the memStore. 
#### Proposal
We can add an optional parameter to the `subscribe` method, to let the caller decide on which store to subscribe, `store` or `memStore` (it can be a simple boolean called useMemStore with false = store, true = memStore and default to false).

**Comment by Gudahtt** [comment]
Great work on this @mikesposito ! I'll leave some comments here.

>2.3: Support optional parameter to not change selected account

Have you considered removing account switching from this method altogether? That would make the method simpler, closer to what mobile has if you take the patch into consideration. On the extension, `addNewAccount` is only called in one place (in `actions.js`) so it would be easy to add a call to `setSelectedAddress` after that call.

Just an idea though; making that step optional sounds good to me as well.


>3.1: Seed phrase should be handled as array of integers instead of string

In other packages we've been using Uint8Array for byte data. Do  think that would be suitable here as well?

We'll still need to convert it to an array of integers on the extension (just for the background <=> UI communication layer, which only supports JSON), but we can save that translation step for that communication layer. That might match expectations on mobile better, where they would never have any need to use an array of integers.

>4.2: Remove account operation's side effects responsibility should stay with the clients

>We should leave to the extension the responsibility to call these two functions before or after calling the core KeyringController's removeAccount.

Agreed that this responsibility belongs with the clients, but I wanted to suggest an alternative to making these calls directly. The preferences controller and the permissions controller can be updated to accept an event handler for when accounts are changed, then they can remove invalid state upon account removal internally. This lets each controller be responsible for the validity of its own state, removing the possibility that someone forgets to call these methods.

>5.4: Support optional parameter to not change selected account

Similar to 2.3, we could consider dropping this step altogether, moving the account switching on extension to the UI layer

**Comment by Gudahtt** [comment]
Regarding the steps that call `destroy` / `dispose` on the keyring, I am conflicted about that. Some hardware wallets do need to be notified when they're no longer expected to be used, so some cleanup can occur. We can probably expect the same use case to appear for snaps at some point as well. So perhaps the keyring controller should be responsible for calling an optional `destroy` method whenever its dropping a reference to a keyring.

In the case where a keyring is "destroying itself" (i.e. the last account is removed), I guess it's possible for the keyring to know to call destroy internally as well. But this doesn't handle the locking case. Whereas if the keyring controller was responsible for calling destroy, it would be easier for us to guarantee that it's always called when the keyring is dropped.

**Comment by Gudahtt** [comment]
>6.2: Session storage clearing should also remain in the extension

Agreed! Perhaps we can put this in an event handler for the `lock` event

>7.1: Leave to the extension the responsibility to avoid multiple UI submissions

Hmm, not sure about this one. This is tricky because there can be multiple windows opened, and because the background <=> UI communication is async. The simplest way to ensure we don't have two "first" HD keyrings is to protect against this in the background.

The mutex in the core keyring controller protects against _simultaneous_ attempts to create a new vault, but it doesn't protect against sequential attempts. So it would still be possible for the UI to be in a state where it _thinks_ there is no vault so it asks for a new one, but by the time the request gets to the background, a vault had been created as a result of another request. Then that vault would get wiped out, potentially losing a private key that someone thought was the primary key for their wallet.

Perhaps the extension has greater needs here because of the multi-process architecture. But even for mobile it probably couldn't hurt to ensure there was no vault before creating a new vault. Or maybe we could leave this check in the extension for now.

**Comment by Gudahtt** [comment]
>8.3: Leave account re-creation and balance fetching to the extension

Oops, I missed this from the analysis! Mobile actually does the same thing, here: https://github.com/MetaMask/metamask-mobile/blob/bdbc865009b9acb4b4068aeefd907de87fd85c2e/app/core/Vault.js#L72

It seems OK to leave this with the clients, but there is an opportunity to make this shared at least.

>9.1: Leave latest block check in the extension

For the scope of this project, this sounds good to me. But I'm not sure why this check is even needed. I was planning to investigate and potentially remove it altogether.

>11: verifyPassword

Part of the accounts team's plan was to make the core keyring controller aligned with extension here, removing the need to store the password at all. Perhaps this would be a better alternative than adding an additional equivalent method.

>14.2: Allow memStore event subscription

>We can add an optional parameter to the subscribe method, to let the caller decide on which store to subscribe, store or memStore (it can be a simple boolean called useMemStore with false = store, true = memStore and default to false).

This would be tricky because `subscribe` is part of the base controller.

The accounts team planned to solve this by refactoring the keyring controller to use base controller v2, which allows a single store to include persisted and non-persisted state. Then we could use a single subscribe function, having no need for two. Perhaps we could solve it in the same way? I am not aware of any blockers to use adopting the v2 API. Something to consider at least.

**Comment by mikesposito** [comment]
Thanks for your comments @Gudahtt! I’ll reply to some of your comments here

#### 2.3
> Have you considered removing account switching from this method altogether? That would make the method simpler, closer to what mobile has if you take the patch into consideration. On the extension, addNewAccount is only called in one place (in actions.js) so it would be easy to add a call to setSelectedAddress after that call.

Proposal edited

#### 3.1, 8.1
> In other packages we’ve been using Uint8Array for byte data. Do think that would be suitable here as well?
Definitely!

Proposal edited

#### 4.2, 8.2
> Agreed that this responsibility belongs with the clients, but I wanted to suggest an alternative to making these calls directly. The preferences controller and the permissions controller can be updated to accept an event handler for when accounts are changed, then they can remove invalid state upon account removal internally. This lets each controller be responsible for the validity of its own state, removing the possibility that someone forgets to call these methods.

What you are suggesting here is to add something like an `onAccountRemoved` method in each involved controller, that will be called from `MetamaskController` upon account removal?

#### 5.4
> Similar to 2.3, we could consider dropping this step altogether, moving the account switching on extension to the UI layer

Proposal edited

#### 6.2 
> Agreed! Perhaps we can put this in an event handler for the lock event

Proposal edited

#### 7.1
> Hmm, not sure about this one. This is tricky because there can be multiple windows opened, and because the background <=> UI communication is async. The simplest way to ensure we don’t have two “first” HD keyrings is to protect against this in the background.

Oh, right! This sounds reasonable. I edited the proposal

#### 8.3
> It seems OK to leave this with the clients, but there is an opportunity to make this shared at least.

Comparing how clients do that, I would say that mobile is more efficient as it keeps a count of pre-existing accounts instead of checking each balance (also, there could be a case where Account 1 has no balance while Account 2 does I guess).

Not sure if we should also make shared the recreation of accounts outside the HD keyring though. I think we should take care of the QR Keyring for sure, that mobile recreates manually while the extensions doesn’t care as it handles the QRKeyring directly without passing through EthKeyringController.

#### 11
> Part of the accounts team’s plan was to make the core keyring controller aligned with extension here, removing the need to store the password at all. Perhaps this would be a better alternative than adding an additional equivalent method.

Proposal edited

#### 14.2
> This would be tricky because subscribe is part of the base controller.

I edited the proposal to update the core KeyringController to BaseControllerV2

**Comment by Gudahtt** [comment]
>What you are suggesting here is to add something like an onAccountRemoved method in each involved controller, that will be called from MetamaskController upon account removal?

What I had in mind was something more like an `onAccountsChanged` event listener, which we could pass into any controller that cares about accounts. They can listen for that event to detect when accounts are removed, and respond accordingly. That way we never have to remember to call it.

**Comment by Gudahtt** [comment]
This plan looks good to me! Some pending discussion on point v4.2 but just on the details; I agree that it should stay with clients and that was the most important point there.
