### ISSUE TITLE
Default commit message when using squash becomes the branch name which results in no release

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/core#1112]
After running the `create-release-branch` script, the commit message matches the pattern `Release <version>` with the branch following `Release/<version>`. If you use squash on a release PR on github, the commit message becomes the branch name, causes the release to be skipped.

To fix this issue, the release script should allow both patterns.

**Comment by Gudahtt** [comment]
Currently it's set to use the PR title for the commit message by default when you squash & merge.

The PR title defaults to the commit message if it's a single commit, but it defaults to the branch name if there are multiple. So the current behavior is correct if you create a PR before updating the changelog. But if you update the changelog first, then create the PR, it has the wrong default title.

**Comment by Gudahtt** [comment]
We can update CI to accept either version, so that the default title always works.

**Comment by Gudahtt** [comment]
I have attempted this here: https://github.com/MetaMask/action-is-release/pull/6

**Comment by mcmire** [comment]
Since this issue was created, we've updated `action-is-release` and [changed the `commit-starts-with` option to accept "Release/[version]"](https://github.com/MetaMask/core/blob/27056aca5d43f5d598f456c1cfa6e6e84a84ea87/.github/workflows/main.yml#L38) as an acceptable commit message. We haven't had any issues with this in a while, so I think we can call this fixed.
