### ISSUE TITLE
[Epic] Convert to monorepo

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/core#322]
By iterating in the approval controller, I've bumped us up two major versions, and with #321, it will be a third. We should publish all controllers as individual packages, and turn this into a monorepo.

**Comment by brad-decker** [comment]
When using a monorepo, my preferred practice for packages is to keep the versions linked so that there is never a discrepancy in version number across packages. React, and babel are good examples of this. I don't think we want our controllers in different version states; thus, it might not solve the particular problem stated in the description.

**Comment by brad-decker** [comment]
This would also require a significant rethinking of the messaging proposal to have each controller in its separate package.

**Comment by mcmire** [comment]
Converting this repo into a monorepo is now a goal of the newly established core team and it is something we will be aiming to complete by end of Q2.

As it relates to the discussion above, we have decided that we do not want to synchronize versions among all of the packages in this repo. Not all of the packages will be related to each other, and we want to be able to give ourselves and product teams the independence to maintain packages with as little coupling as possible.

Consult [this document](https://docs.google.com/document/d/1G3M-lcwvfNFs3Tq4lVzhywqzYhCqPqBN7c5n8TC9sWM/edit) for more information on our plan going forward.

**Comment by Gudahtt** [comment]
This was completed in https://github.com/MetaMask/core/pull/831
