### ISSUE TITLE
[assets-controllers] Fetch token rates in batches to avoid hitting limits

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3573]
We currently fetch the token rates for all tokens (for a given network) in a single call. However, the CoinGecko API we're currently using supports a maximum of 10 token addresses in a single request. Beyond that, it throws an error. The price API that we're considering migrating to has a similar limit of 15 addresses.

We should update the `TokenRatesController` to batch requests by a configurable amount (10 for now) to avoid hitting this error.

**Comment by NicolasMassart** [comment]
Also, for the Coingecko it's a deliberate choice to limit to 10, we receive a clear error message :
```json
{"timestamp":"2023-11-23T14:08:29.074+00:00","error_code":10012,"status":{"error_message":"Number of contract addresses in the request exceeds the allowed limit (10 addresses). Please note that to ensure fair usage and prevent abuse, the allowed limit may be adjusted periodically. To enjoy higher allowed limit, please subscribe to Demo plan or a paid plan at https://www.coingecko.com/en/api/pricing"}}
```

For the Codefi Price API, the limit of 15 was found by trial and error as the result is gateway timeout. So we can't tell if it's a deliberate limit or one that's caused by a memory limit or anything else including a bug.

So, on the Codefi API, instead of just sending the requests by chunks, we also have to investigate the root cause for the api non responding in some cases. It may reveal an issue that has to be fixed.

If we realise that this issue can't easily be fixed but has a deterministic way to happen, like always over 15 tokens) then we should return an error message like Coingecko, clearly indicating the limit.

**Comment by NicolasMassart** [comment]
Note that I think Coingecko implemented that limit recently and have not documented it yet. I can't find anything about it.

**Comment by tommasini** [comment]
Mobile team last update:

We change from the coin gecko endpoint to price api endpoint as we can verify [here](https://github.com/MetaMask/core/tree/assets-controllers-v7-token-rate-controller-patch), and it's working as expected

**Comment by DDDDDanica** [comment]
Updates: 
Validated again from my side, and it seems like the issue has been solved
```
https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x0104f019c8889BdabC62aE6C7b84F6f2ed351133,0x767FE9EDC9E0dF98E07454847909b5E959D7ca0E,0x6123B0049F904d730dB3C36a31167D9d4121fA6B,0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984,0xCc802c45B55581713cEcd1Eb17BE9Ab7fcCb0844,0x75231F58b43240C9718Dd58B4967c5114342a86c,0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84,0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE,0x2b591e99afE9f32eAA6214f7B7629768c40Eeb39,0x0001A500A6B18995B03f44bb040A5fFc28E45CB0,0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2&vs_currencies=eth
<img width="1035" alt="Screenshot 2023-11-30 at 15 47 48" src="https://github.com/MetaMask/core/assets/12678455/50033fcc-f223-4430-9074-b2097b7048ab">

```

**Comment by cryptodev-2s** [comment]
Rate limit occur error after making five consecutive calls. The error response is as follows:
 `{
  status: {
    error_code: 429,
    error_message: "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}`
