### ISSUE TITLE
[base-controller] `getRestricted` infers the wrong types when it has no allowed actions/events

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/core#3648]
When constructing a restricted controller messenger with no allowed actions, it will infer the "allowed action" type as encompassing all actions. This puts the types and runtime behavior out-of-sync; at runtime, no allowed actions means you can't call any external actions, but at the type level it acts as though you could call all of them.

Everything applies equally to events as well; the same problem is present for both actions and events.

For example:

```TypeScript
type MessageEvent = {
  type: 'MessageController:message';
  payload: [string];
};
type OtherEvent = {
  type: 'OtherController:other';
  payload: [unknown];
};

// Global messenger setup with two events: one for the MessengerController, and one external.
const controllerMessenger = new ControllerMessenger<
  never,
  MessageEvent | OtherEvent
>();
// No explicit type parameters given, they are inferred.
// Note that no allowed events are specified, so "OtherController:other" should be disallowed
const restrictedControllerMessenger = controllerMessenger.getRestricted({
  name: 'MessageController',
});

// This should result in a type error, but it does not. Instead it throws at runtime.
// "AllowedActions" has been inferred as being all actions
restrictedControllerMessenger.subscribe(
  'OtherController:other',
  () => undefined,
);
```

This is easily addressed by explicitly declaring the type parameter as `never` when constructing the `RestrictedMessengerController`. For example:

```TypeScript
// following from the same global ControllerMessenger as the above example

// Explicit type parameters given
const restrictedControllerMessenger = controllerMessenger.getRestricted<
  'MessageController',  // "name"
  never,                            // "allowedActions"
  never                            // "allowedEvents"
>({
  name: 'MessageController',
});

// This now correctly results in a type error
restrictedControllerMessenger.subscribe(
  'OtherController:other',
  () => undefined,
);
```

However, needing to explicitly declare type parameters for the empty case is not great. It's verbose, and makes this a bit more difficult to use.

We should investigate and find a way to ensure the inferred type is correct. If that's not possible, we should at least document this issue somewhere, so people are less likely to be caught off guard by it.

**Comment by MajorLift** [comment]
It seems like this applies not just to the empty case, but to any case where the allowed actions/events listed at the value level is narrower than the full `Allowed{Actions,Events}` union defined in the controller.

The 2nd and 3rd generic params of `getRestricted` default to the full `Allowed{Actions,Events}` unions when omitted. The problem is that if the value-level `allowed{Actions,Events}` arrays don't list the full unions (including being empty arrays or undefined), the type-level generic params are still inferred as the full union. The only way to override this is to explicitly pass in the narrower unions as generic params.

Having the `Allowed{Actions,Events}` generic params in `getRestricted` simply default to `never` would be safer at the expense of a worse developer experience (having to specify the same list twice at the value-level and type-level). Inferring the generic params from `allowed{Actions,Events}` would be ideal, but it's not clear whether that's possible.

**Comment by MajorLift** [comment]
One thing I hadn't considered is that our javascript clients are unable to supply generic arguments when calling `getRestricted`, so we can't be too restrictive with the default behavior we implement.

**Comment by MajorLift** [comment]
For downstream JavaScript clients, the generic params are not available at all. This makes it completely unambiguous that the intention behind omitting `allowed{Actions,Events}` params or passing in an empty array is to enforce an empty allowlist. I agree that always defaulting to `never` for null input would be the correct behavior to implement in this ticket.

Fixing the issue of incomplete allowlists being inferred as complete at the type level should be separated into its own ticket.

**Comment by MajorLift** [comment]
This issue shouldn't be confused as also applying to the generic parameters of the `RestrictedControllerMessenger` class, all five of which are intended to be required with no default arguments provided or allowed. 

- See: https://github.com/MetaMask/metamask-mobile/pull/8607#discussion_r1508097534
