### ISSUE TITLE
`json-rpc-engine`: Replace use of `any` with proper types (non-test files only)

### ISSUE THREAD

**Issue by mcmire** [MetaMask/core#3720]
Look for the following string in non-test files to find these: ``// TODO: Replace `any` with type``

At time of writing, there were 6 instances.

**Comment by MajorLift** [comment]
- Completing this ticket will enable us to take full advantage of the type safety improvements that will be introduced by the [provider alignment technical proposals](https://app.zenhub.com/workspaces/shared-libraries-621e46b4d7103800171d1b02/issues/zh/244). 
- All of the `any` usages in this package are for typing errors in catch blocks. These errors should mostly be aligned to `JsonRpcEngineCallbackError`. 
- `serializeError()` should only be used when sending an error via JSON-RPC. Otherwise, the information in `unknown` errors thrown by middleware should be preserved.

**Comment by MajorLift** [comment]
See previous refactor efforts: https://github.com/MetaMask/json-rpc-engine/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
