### ISSUE TITLE
Convert AssetsContractController from BaseControllerV1 to BaseControllerV2

### ISSUE THREAD

**Issue by desi** [MetaMask/core#4072]
Considering that converting TokenDetectionController to BaseController v2 took longer than expected due to unforeseen changes, we want to be more conscientious about converting AssetsContractController.

Figure out all of the changes we would want to make in upgrading this controller, outline those changes here and create new tickets if appropriate.

**Comment by MajorLift** [comment]
- Define internal messenger actions/events types.
	- Define messenger actions for all public methods of `AssetsContractController` class.
	- Define `AssetsContractControllerActions`, `AssetsContractControllerEvents`, `AssetsContractControllerGetStateAction` (using `ControllerGetStateAction` type), `AssetsContractControllerStateChangeEvent` (using `ControllerStateChangeEvent` type)
- Replace constructor option callbacks with messenger actions/events
	- `onPreferencesStateChange`
		- `PreferencesController:stateChange`
		- Use `PreferencesControllerStateChangeEvent`
	- `onNetworkDidChange`
		- `NetworkController:networkDidChange`
		- Use `NetworkControllerNetworkDidChangeEvent`
	- `getNetworkClientById`
		- `NetworkController:getNetworkClientById`
		- Use `NetworkControllerGetNetworkClientByIdAction`
	- Define `AllowedActions` union type and add the above as its members.
		- Export this type so it's usable by tests and other internal modules, but exclude it as a package-level export.
	- Replace the callback invocations in the constructor with `subscribe()` calls, using the existing listener logic.
- Define `AssetsContractControllerMessenger` using the types defined in the above bullet points.
- `AssetsContractController extends BaseControllerV2`.
- `AssetsContractConfig`
	- Move properties of this type to private class fields of the `AssetsContractController` class.
	- Set default values from `this.defaultConfig` object.
	- Replace `this.configure` calls with assignments to corresponding class fields.
- constructor
  - Replace `super` call so that it conforms to V2 requirements.
  - Remove `this.initialize()`
  - Remove `override name` class field.
- Replace all `private` keywords for class fields and methods with `#` prefix.
- Refactor tests. Use `withController` pattern.|

- Notes:
	- This controller has an empty state object. 
	- Consider replacing type annotation for `SINGLE_CALL_BALANCES_ADDRESS_BY_CHAINID` with `satisfies` keyword.

**Comment by desi** [comment]
All of the steps above are correct. Rename to not be called Controller and remove it from using the BaseController class. This file probably needs a redesign.

**Comment by cryptodev-2s** [comment]
Some functions seems to be just helper function used within the controller only for example `getERC20Standard` which can be private instead
