### ISSUE TITLE
Detail documentation, architecture diagram and How-to guides for Metamask controllers

### ISSUE THREAD

**Issue by ashwinYardi** [MetaMask/core#872]
Is there any standard documentation out there which depicts, exactly how do metamask controllers work? It would be really really helpful if there is a documentation for this. @metamask/controllers is a very powerful, generic and platform agnostic tools for wallets and dapps and imo, sets standard in how the Web3 code with state management should be written.

**Comment by mcmire** [comment]
Hi @ashwinYardi, thanks for bringing this up. We don't have that kind of documentation today, but I agree that some kind of architectural overview would be beneficial, not only for you, but also for us. That said, it depends on what you want to know. At present this repo serves both MetaMask the extension and MetaMask the mobile app, so in order to understand certain pieces of functionality, such as how networks get added or how accounts get added, one would probably have to understand parts of either the extension or mobile app as well in order to get a proper big picture. In other words, there's some architectural cleanup we'd have to do in order to make this repo represent the functionality in MetaMask in a modular, isolated way. That said, we could probably start by explaining the underlying mechanics of the controllers. Each controller inherits from a BaseController and that sets up the state management, so that might be valuable to understand as well as how something would respond to a particular controller's state changes. We plan on making some headway in terms of contributor documentation in an upcoming quarter so this is definitely something we could add to our list. I'll keep this issue open in the meantime in case you think of anything else you'd like us to cover.

**Comment by ashwinYardi** [comment]
Hey @mcmire , thanks for this. I am trying my hands with metamask controllers by writing a short / dirty script which shows how to create account, add custom network and submit a transaction. Having said that, I will also try to put my understanding about each controller in a doc and my blog. Will share here, in case it proves to be helpful for others :)

**Comment by mcmire** [comment]
Yeah that would be great!

**Comment by desi** [comment]
Closing as we have additional issues to cover documentation. Thanks to the author for the discussion! https://github.com/MetaMask/contributor-docs/issues/54
